name: nightly
on:
  schedule:
    - cron: "17 9 * * *"
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: false
jobs:
  nightly:
    uses: ./.github/workflows/tool-nightly.yml
    with:
      ci-image-dir: ci
